language: bash

before_install:
  - bash --version
  - make --version
  - ruby --version
  - gem --version
  - gem install bashcov
  - gem install coveralls
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats

script:
  - bashcov bats test/*.bats
  
after_success:
  - coveralls

notifications:
  email:
    on_success: never
