language: bash

before_install:
  - gem install coveralls
  - git clone --depth=50 --branch=master https://github.com/ctubio/bashcov /home/travis/ctubio/bashcov
  - gem build /home/travis/ctubio/bashcov/bashcov.gemspec
  - gem install /home/travis/ctubio/bashcov/bashcov-1.1.0.gem
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats

script:
  - bashcov make test
  
after_success:
  - coveralls

notifications:
  email:
    on_success: never
