language: bash

branches:
  only:
    - master
    
before_install:
  - gem install coveralls
  - git clone --depth=50 --branch=master https://github.com/ctubio/bashcov /home/travis/ctubio/bashcov
  - cd /home/travis/ctubio/bashcov
  - gem build /home/travis/ctubio/bashcov/bashcov.gemspec
  - gem install bashcov-1.1.0.gem -V
  - cd $TRAVIS_BUILD_DIR
  - gem list
  - gem env
  - which gem
  - ls -la /usr/local/bin
  - ls -la /home/travis/.rvm/gems/*/bin
  - ls -la /home/travis/.rvm/gems/ruby-1.9.3-p551/bin
  - ls -la /home/travis/.rvm/gems/ruby-1.9.3-p551@global/bin
  - ls -la /home/travis/.rvm/rubies/ruby-1.9.3-p551/bin
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats

script:
  - bashcov make test
  
after_success:
  - coveralls

notifications:
  email:
    on_success: never
