language: bash

branches:
  only:
    - master
    
before_install:
  - gem install coveralls
  - git clone --depth=50 --branch=master https://github.com/ctubio/bashcov /home/travis/ctubio/bashcov
  - gem build /home/travis/ctubio/bashcov/bashcov.gemspec
  - gem install bashcov-1.1.0.gem
  - ls /home/travis/.rvm/gems/ruby-1.9.3-p551/bin
  - ls /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/*
  - gem which bashcov-1.1.0
  - bundle show bashcov bashcov
  - bundle show bashcov bashcov-1.1.0
  - export PATH=$PATH:/home/travis/.rvm/gems/ruby-1.9.3-p551/bin
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats

script:
  - bashcov make test
  
after_success:
  - coveralls

notifications:
  email:
    on_success: never
