language: bash

before_install:
  - gem install coveralls
  - gem specific_install https://github.com/ctubio/bashcov
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats

script:
  - bashcov-1.1.0 make test
  
after_success:
  - coveralls

notifications:
  email:
    on_success: never
