language: bash

branches:
  only:
    - master
    
before_install:
  - git clone --depth=50 --branch=master https://github.com/ctubio/bashcov /home/travis/ctubio/bashcov
  - cd /home/travis/ctubio/bashcov
  - gem build /home/travis/ctubio/bashcov/bashcov.gemspec
  - gem install bashcov-*.gem
  - cd $TRAVIS_BUILD_DIR
#  - gem install bashcov
  - gem install coveralls
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats
#  - env

script:
  - make test
  - cat aa  
#after_success:
#  - coveralls

notifications:
  email:
    on_success: never
