language: bash

branches:
  only:
    - master
    
before_install:
#  - gem install coveralls
  - git clone --depth=50 --branch=master https://github.com/ctubio/bashcov /home/travis/ctubio/bashcov
  - cd /home/travis/ctubio/bashcov
  - gem build /home/travis/ctubio/bashcov/bashcov.gemspec
  - gem install bashcov-*.gem
  - cd $TRAVIS_BUILD_DIR
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats

script:
  - bashcov make test
  
after_success:
  - cd $TRAVIS_BUILD_DIR
  - coveralls

notifications:
  email:
    on_success: never
