#!/bin/bash
# BEGIN of INSTALL file, mighty installer.
# runs from any path at your machine, just type in your tty:
#   bash -c "$(curl -s https://ctubio.github.io/INSTALL)";
## How appropiate, you install like a cow.
# but.. look behind you! a Three-Headed Monkey!
echo -e "Yikes!\n" \
  "Let's install some initial files for your new project.\n" \
  "- Install path: ${PWD}";
read -p "Are you sure? [y/N] `echo $'\n> '`" -n 1 -r && echo;
case $REPLY in
  [yY][eE][sS]|[yY])
    echo "Fetching the latest stable release.." && \
    read tag_name created_at tarball_url <<< $( \
      curl -s https://api.github.com/repos/ctubio/ctubio.github.io/releases/latest | \
        grep "\"tag_name\"\|\"created_at\"\|\"tarball_url\"" | \
          sed -e "s/.*: \"//" -e "s/\".*//" \
    ) && \
    echo -e " - ${tag_name} last modified: `echo ${created_at/T/ } | tr -d Z`" \
      "\nDownloading your new project files, please wait.." && \
    curl -Ls "${tarball_url}" | \
      tar --wildcards --backup=simple --show-transformed --strip 2 -vxzf - */src && \
    ls -hal --color;
    ;;
  *)
    echo "wtf.. cd to a nicer path and type again:" && \
    sed -e "s/^#  //" -e '4q;d' <<< "$( \
      test ! -z "$BASH_EXECUTION_STRING" && \
        echo "$BASH_EXECUTION_STRING" || cat "$0" \
    )" && \
    echo -n "anyway.. ";
    ;;
esac;
if [ "$?" -ne "0" ]; then
  echo "oh well, something went wrong..";
else
  echo "all done.. Thank you!";
fi;
# and very special thanks to RON GILBERT for Monkey Island.
# and remember! Never pay more than 20 bucks for a computer game.
# and END
